_target_: src.models.cancer_image_module.CancerImageClassifier

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.001
  weight_decay: 0.1

net:
  _target_: src.models.nets.vit.ViT
  name: vit_b_16
  output_size: 1
  pretrained: True