_target_: src.models.oxford_seg_module.SegmentationClassifierModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.001
  weight_decay: 0.0

image_size: 101
in_image_channels: 1
output_classes: 1