_target_: src.datamodules.cancer_data.CancerDataModule
comp_name: histopathologic-cancer-detection
data_dir: ${paths.data_dir}
downsample_n: -1
validation_split: 0.2
batch_size: 1024
num_workers: 7
pin_memory: True
image_size: 32
