_target_: src.datamodules.cancer_module.CancerDataModule
comp_name: histopathologic-cancer-detection
data_dir: ${paths.data_dir}
downsample_n: 20000
validation_split: 0.2
batch_size: 1024
num_workers: 2
pin_memory: True
