defaults:
  - _self_
  - datamodule: stock_candles
  - logger: wandb
  - model: candlestick_resnet
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml

task_name: train

checkpoint_reference: null

seed: 1729

wandb_enabled: false