defaults:
  - _self_
  - callbacks: default.yaml
  - datamodule: gr_contrails
  - logger: wandb
  - model: gr_contrails_unet
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml

task_name: train

checkpoint_reference: null

seed: 1729

wandb_enabled: false