defaults:
  - _self_
  - callbacks: early_stopping
  - datamodule: cancer
  - logger: wandb
  - model: cancer_conv2d
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml

task_name: train

checkpoint_reference: null

seed: 1729