defaults:
  - _self_
  - datamodule: cancer
  - callbacks: default
  - logger: wandb
  - model: cancer_conv2d
  - trainer: default
  - hydra: default
  - paths: default

task_name: train

checkpoint_reference: null

seed: 8128

wandb_enabled: false