defaults:
  - _self_
  - callbacks: early_stopping
  - datamodule: oxford
  - logger: wandb
  - model: oxford_unet
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml

task_name: train

checkpoint_reference: null

seed: 1729